export const SKILL_DICTIONARY = {
  frontend: [
    "react",
    "next.js",
    "nextjs",
    "javascript",
    "js",
    "html",
    "css",
    "tailwind",
    "tailwindcss",
    "redux",
    "typescript",
    "ts",
    "vue",
    "angular",
    "svelte",
  ],
  backend: [
    "node.js",
    "nodejs",
    "node",
    "express",
    "express.js",
    "rest api",
    "restful api",
    "graphql",
    "mongodb",
    "sql",
    "postgresql",
    "postgres",
    "mysql",
    "prisma",
    "python",
    "django",
    "flask",
    "java",
    "spring boot",
    "ruby on rails",
    "php",
    "laravel",
  ],
  tools: [
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "vercel",
    "docker",
    "aws",
    "ci/cd",
    "kubernetes",
    "k8s",
    "linux",
    "bash",
    "npm",
    "yarn",
    "webpack",
    "vite",
    "jest",
    "cypress",
    "postman",
    "figma",
  ],
  concepts: [
    "authentication",
    "auth",
    "testing",
    "performance",
    "responsive design",
    "deployment",
    "api integration",
    "security",
    "seo",
    "web accessibility",
    "a11y",
    "state management",
    "microservices",
    "serverless",
    "database design",
  ],
  softSkills: [
    "communication",
    "collaboration",
    "problem solving",
    "problem-solving",
    "leadership",
    "ownership",
    "teamwork",
    "time management",
    "adaptability",
    "agile",
    "scrum",
    "mentoring",
  ],
};
